// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
  username
) VALUES (
  ?
)
`

func (q *Queries) CreateUser(ctx context.Context, username string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, username)
}
